services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Wazum\RenderDependencyRecorder\:
    resource: '../Classes/*'

  Wazum\RenderDependencyRecorder\Recorder\RecorderContext:
    public: true

  Wazum\RenderDependencyRecorder\Middleware\RecorderMiddleware:
    public: true

  Wazum\RenderDependencyRecorder\Writer\RequestFileWriter:
    public: true

  Wazum\RenderDependencyRecorder\View\RecordingViewFactory:
    decorates: TYPO3\CMS\Core\View\ViewFactoryInterface
    arguments:
      $inner: '@Wazum\RenderDependencyRecorder\View\RecordingViewFactory.inner'
      $recorder: '@Wazum\RenderDependencyRecorder\Recorder\RecorderContext'
